/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as TeamsRouteRouteImport } from './routes/teams/route'
import { Route as ManageRouteRouteImport } from './routes/manage/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as ManageIndexRouteImport } from './routes/manage/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as OrgOrgIdRouteImport } from './routes/org.$orgId'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as JoinJoinCodeRouteImport } from './routes/join.$joinCode'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as ManageScoreMatchIdRouteImport } from './routes/manage/score/$matchId'
import { Route as ManagePostmatchProcessMatchIdRouteImport } from './routes/manage/postmatch-process/$matchId'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRouteRoute = TeamsRouteRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRouteRoute = ManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRouteRoute,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRouteRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRouteRoute,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdRoute = OrgOrgIdRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinJoinCodeRoute = JoinJoinCodeRouteImport.update({
  id: '/join/$joinCode',
  path: '/join/$joinCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageScoreMatchIdRoute = ManageScoreMatchIdRouteImport.update({
  id: '/score/$matchId',
  path: '/score/$matchId',
  getParentRoute: () => ManageRouteRoute,
} as any)
const ManagePostmatchProcessMatchIdRoute =
  ManagePostmatchProcessMatchIdRouteImport.update({
    id: '/postmatch-process/$matchId',
    path: '/postmatch-process/$matchId',
    getParentRoute: () => ManageRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteRouteWithChildren
  '/teams': typeof TeamsRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/policy': typeof PolicyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/tos': typeof TosRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/org/$orgId': typeof OrgOrgIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/manage/': typeof ManageIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/manage/postmatch-process/$matchId': typeof ManagePostmatchProcessMatchIdRoute
  '/manage/score/$matchId': typeof ManageScoreMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/policy': typeof PolicyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/tos': typeof TosRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/org/$orgId': typeof OrgOrgIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/manage': typeof ManageIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/manage/postmatch-process/$matchId': typeof ManagePostmatchProcessMatchIdRoute
  '/manage/score/$matchId': typeof ManageScoreMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteRouteWithChildren
  '/teams': typeof TeamsRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/policy': typeof PolicyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/tos': typeof TosRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/org/$orgId': typeof OrgOrgIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/manage/': typeof ManageIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/manage/postmatch-process/$matchId': typeof ManagePostmatchProcessMatchIdRoute
  '/manage/score/$matchId': typeof ManageScoreMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage'
    | '/teams'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/policy'
    | '/profile'
    | '/register'
    | '/tos'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/join/$joinCode'
    | '/match/$matchId'
    | '/org/$orgId'
    | '/team/$teamId'
    | '/teams/$teamId'
    | '/manage/'
    | '/teams/'
    | '/manage/postmatch-process/$matchId'
    | '/manage/score/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/policy'
    | '/profile'
    | '/register'
    | '/tos'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/join/$joinCode'
    | '/match/$matchId'
    | '/org/$orgId'
    | '/team/$teamId'
    | '/teams/$teamId'
    | '/manage'
    | '/teams'
    | '/manage/postmatch-process/$matchId'
    | '/manage/score/$matchId'
  id:
    | '__root__'
    | '/'
    | '/manage'
    | '/teams'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/policy'
    | '/profile'
    | '/register'
    | '/tos'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/join/$joinCode'
    | '/match/$matchId'
    | '/org/$orgId'
    | '/team/$teamId'
    | '/teams/$teamId'
    | '/manage/'
    | '/teams/'
    | '/manage/postmatch-process/$matchId'
    | '/manage/score/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageRouteRoute: typeof ManageRouteRouteWithChildren
  TeamsRouteRoute: typeof TeamsRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PolicyRoute: typeof PolicyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  TosRoute: typeof TosRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  JoinJoinCodeRoute: typeof JoinJoinCodeRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  OrgOrgIdRoute: typeof OrgOrgIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof TeamsRouteRoute
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRouteRoute
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId': {
      id: '/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof OrgOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$joinCode': {
      id: '/join/$joinCode'
      path: '/join/$joinCode'
      fullPath: '/join/$joinCode'
      preLoaderRoute: typeof JoinJoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/score/$matchId': {
      id: '/manage/score/$matchId'
      path: '/score/$matchId'
      fullPath: '/manage/score/$matchId'
      preLoaderRoute: typeof ManageScoreMatchIdRouteImport
      parentRoute: typeof ManageRouteRoute
    }
    '/manage/postmatch-process/$matchId': {
      id: '/manage/postmatch-process/$matchId'
      path: '/postmatch-process/$matchId'
      fullPath: '/manage/postmatch-process/$matchId'
      preLoaderRoute: typeof ManagePostmatchProcessMatchIdRouteImport
      parentRoute: typeof ManageRouteRoute
    }
  }
}

interface ManageRouteRouteChildren {
  ManageIndexRoute: typeof ManageIndexRoute
  ManagePostmatchProcessMatchIdRoute: typeof ManagePostmatchProcessMatchIdRoute
  ManageScoreMatchIdRoute: typeof ManageScoreMatchIdRoute
}

const ManageRouteRouteChildren: ManageRouteRouteChildren = {
  ManageIndexRoute: ManageIndexRoute,
  ManagePostmatchProcessMatchIdRoute: ManagePostmatchProcessMatchIdRoute,
  ManageScoreMatchIdRoute: ManageScoreMatchIdRoute,
}

const ManageRouteRouteWithChildren = ManageRouteRoute._addFileChildren(
  ManageRouteRouteChildren,
)

interface TeamsRouteRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const TeamsRouteRouteChildren: TeamsRouteRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

const TeamsRouteRouteWithChildren = TeamsRouteRoute._addFileChildren(
  TeamsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageRouteRoute: ManageRouteRouteWithChildren,
  TeamsRouteRoute: TeamsRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PolicyRoute: PolicyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  TosRoute: TosRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  JoinJoinCodeRoute: JoinJoinCodeRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  OrgOrgIdRoute: OrgOrgIdRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
